import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import Cta from "@/components/cta/cta";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:
    "Reach To All Corners of The World With Us | PT. ANUGERAH MULTI LOGISTIK",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Cta />
        <Footer />
      </body>
    </html>
  );
}
